on:
  pull_request:

name: Lint

jobs:
  shellcheck:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-arm64
    permissions:
      contents: read
    steps:
      - uses: runs-on/action@46910bf61b41721b0579f237e186afb35477007a # v2.3.0
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
